name: publish
run-name: Publishing to Pypi
on:
  push:
    branches:
      - main
jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Put venv in project directory
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          python -m poetry install
